### ISSUE TITLE
CANNOT SWITCH TO DARK MODE

### ISSUE THREAD

**Issue by dimaslanjaka** [cdcsgit/lognote#10]
when I touch apply dark mode, it revert back to light mode. even I restart the application

I touch `apply` and switch like this

![image](https://github.com/cdcsgit/lognote/assets/12471057/f8c868ba-008c-41f7-9a24-72100fada202)

after I touch X on setting window, it back to light mode 

![image](https://github.com/cdcsgit/lognote/assets/12471057/6795f72d-e2e0-4f53-ad77-75ee0397dda8)

even I restarted the app, no changes

**Comment by cdcsgit** [comment]
Changes are saved only when you press the OK button at the bottom.
Please refer to the comment on issue #11

**Comment by cdcsgit** [comment]
Applied to v 0.3.6
