### ISSUE TITLE
CANNOT RESIZE WINDOW ON SETTINGS WINDOW

### ISSUE THREAD

**Issue by dimaslanjaka** [cdcsgit/lognote#11]
the height of setting windows larger than my screen, when i swipe the border of windows, it never resized

![image](https://github.com/cdcsgit/lognote/assets/12471057/ef3a2ac3-2945-464c-8d53-8bcb12bbcf21)

when I swipe the border, the window goes down

![image](https://github.com/cdcsgit/lognote/assets/12471057/46966e81-cb70-4cb7-9608-942d09accdad)

**Comment by cdcsgit** [comment]
I attached a file that resized the Appearance settings window (minimum 800->500).
Use it first and I will include it in the next version release.
[LogNote.jar.zip](https://github.com/cdcsgit/lognote/files/14394862/LogNote.jar.zip)

**Comment by cdcsgit** [comment]
Applied to v 0.3.6
