### ISSUE TITLE
Asking for help to make the lognote project run on windows

### ISSUE THREAD

**Issue by RishiDt** [cdcsgit/lognote#17]
Hi, 
I hope you are well. I wanted your help on how to actually run the lognote project on windows. I have read the readme. The command requires a lognote.jar file. that suggests (I may be wrong) that the project needs to be compiled and archived. I am new to this but I need a better logcat experience. I hope to get a reply from you soon.

-Rishikesh (Flutter app developer, Asia, India)

**Comment by cdcsgit** [comment]
Hi.
You can download the lognote.jar file from releases.
LogNote-1.0.zip from releases(https://github.com/cdcsgit/lognote/releases)
And unzip it.

Run the following command "start javaw -Dfile.encoding=utf8 -Xmx1024m -jar LogNote.jar"
Or, run lognote.bat included in the zip.

**Comment by RishiDt** [comment]
Thank you. I do use git for vcs. but never used the release feature of github. Thanks again. I believe when people are getting paid to write code for making softwares, there is someone creating it for giving a hand to someone. Best of luck.
