### ISSUE TITLE
can't filter for package name

### ISSUE THREAD

**Issue by zxt5105515** [cdcsgit/lognote#2]
the pid will change when app restart ,it's annoying to find the pid then change the pid. thx

**Comment by cdcsgit** [comment]
To filter by package name, process information must be read periodically.
There are currently no plans.
It seems that you can filter by specific strings or tags.

**Comment by cdcsgit** [comment]
There is a workaround.
If you are using Linux, run the attached script(find the package name and run logcat). 
If you are using another OS, you need to create a script.

Run it like this:
Set "PACKAGE", "ADB", "DEVICE" values in script.
./logcat_package.sh > save_file.log
Select LogNote > File > Follow menu
Select the save_file.log file from the dialog

Follow mode reads appended logs from a file.
[logcat_package.sh.zip](https://github.com/cdcsgit/lognote/files/10832715/logcat_package.sh.zip)
