### ISSUE TITLE
lognote hangs while collecting adb logs

### ISSUE THREAD

**Issue by wshamroukh** [cdcsgit/lognote#5]
While adb caglogs are being collected live, and if you click on any line, the lognote would freeze and hange until the cable is removed from the device. But again you will face hangs afterwards too.

The one that was working for me fine was v0.3.0
I am tried v0.3.4 also hangs 

It is a nice tool and I like it.. If there is anything that you need me to collect to figure out the hang, please let me know

**Comment by cdcsgit** [comment]
Please let us know your usage environment(pc os).
If possible, please let me know which version the issue started to occur between 0.3.0 and 0.3.4.
​

**Comment by cdcsgit** [comment]
There was a bug in the command to get the process list.
It will be fix next version.

Here's how to avoid bugs in version 0.3.4.
1. Set not to import process list
a. Settings > Log cmd (adb)
b. Update process info timeout : 0
OR
2. Set device name
a. Click the "Refresh" button(to the right of the "Disconnect" button)
- add result of "adb devices" to commbo box
b. Select the device name from the combo box (to the left of the "Connect" button)
c. Click "Start" button

**Comment by cdcsgit** [comment]
> I was originally on 0.3.0 where things were working fine.. Then upgraded to 0.3.3 which had this hang issue, and today i saw v0.3.4 and I used it hoping it doesn't have the hang issue, but it was there.. So i used 0.3.0 and I did not face the issue again. I am using Windows 10 here.

Please see the comment I just added.

**Comment by Uzver123** [comment]
I have version 0.3.4 and still same bug with freezing almost instantly and had to terminate Java, Window 10 x64,  

**process info timeout : 0**

fix this so far no more freezes.
