### ISSUE TITLE
LogNote constantly Freeze and had to terminate with task manager.

### ISSUE THREAD

**Issue by Uzver123** [cdcsgit/lognote#6]
I don't have Java installed, i used version from portableapps and also OpenJDK platform, LogNote always freezing when using filters weather i use static log file or connect trough ADB.

Windows 10 x64.

**Comment by cdcsgit** [comment]
Does "portableapps" mean downloaded from somewhere other than the github release?
Please check the #5 issue.
If this is a different, please let me know how to reproduce it.

**Comment by Uzver123** [comment]
Its same, i responded in other thread.

**Comment by cdcsgit** [comment]
It will be fix next version.
