### ISSUE TITLE
Filter by tag: Inconsistency of $

### ISSUE THREAD

**Issue by IgorEisberg** [cdcsgit/lognote#8]
Hi, thanks for the excellent log viewer.
This is a minor issue, but something annoying nonetheless.
When filtering by tag using a regex pattern, `^` always matches the beginning of the tag, but `$` doesn't always match the end of it.
Example:
```
12-05 22:22:48.538   728  1160 I zygote  : Verified 41637 classes from mainline modules in 4.623s
```
Filtering by `^zygote$` correctly finds this line.
However:
```
12-05 22:23:37.314  1436  1753 D PackageManager: writeLegacyPermissionState for user 0 in 13 ms.
```
Filtering by `^PackageManager$` finds nothing.
Filtering by `^PackageManager:$` finds the line, but the `:` is not really part of the tag, just like it's not part of the `zygote` tag (filtering by `^zygote:$` or `^zygote  :$` finds nothing).

Hope you can patch it up.
Thanks in any case.

**Comment by IgorEisberg** [comment]
> This occurs because the character following the tag is not a white space. Please use ".?" temporarily. ^zygote.?$ ^PackageManager.?$
> 
> I will improve it in the next version.

Been using `\b` as a workaround for now, always works.
```
^(zygote|PackageManager)\b
```

**Comment by cdcsgit** [comment]
Applied to v 0.3.6
